#!/usr/bin/env python3
"""
TrustCheck Scraper Bot
Automatycznie wykrywa oszustwa z grup Facebook i dodaje do bazy
"""

import time
import json
from datetime import datetime
from config import Config
from modules.facebook_scraper import FacebookScraper
from modules.vision_processor import VisionProcessor
from modules.trustcheck_api import TrustCheckAPI

def map_scam_type_to_reason(scam_desc: str, screenshot_type: str) -> str:
    """Mapuje opis oszustwa na kategorię w TrustCheck"""
    desc_lower = scam_desc.lower()
    
    if any(word in desc_lower for word in ['wyłudzenie', 'oszustwo', 'scam', 'przekręt']):
        return 'SCAM'
    elif any(word in desc_lower for word in ['spam', 'reklama', 'telemarketing']):
        return 'SPAM'
    elif any(word in desc_lower for word in ['towar', 'nie wysłał', 'nie otrzymał']):
        return 'TOWAR'
    else:
        return 'SCAM'

def calculate_rating(confidence: str) -> int:
    """Oblicza rating na podstawie confidence"""
    mapping = {
        'high': 1,
        'medium': 2,
        'low': 3
    }
    return mapping.get(confidence, 2)

def process_screenshot(post: dict, vision: VisionProcessor, api: TrustCheckAPI) -> bool:
    """
    Przetwarza pojedynczy screenshot i dodaje zgłoszenie
    """
    print(f"\n{'='*60}")
    print(f"📄 Post: {post['post_url']}")
    print(f"👤 Autor: {post['author']}")
    
    # Analiza tekstu posta (szybka prefiltracja)
    text_analysis = vision.analyze_post_text(post['text'])
    if not text_analysis.get('is_scam_report'):
        print("⏭️  Pomijam - nie jest to zgłoszenie oszustwa")
        return False
    
    # Przetwarzaj każdy screenshot
    for img_url in post['images'][:3]:  # Max 3 obrazki na post
        print(f"🖼️  Analizuję: {img_url[:60]}...")
        
        # GPT-4 Vision - ekstrakcja danych
        extracted = vision.analyze_screenshot(img_url)
        
        if not extracted:
            print("⚠️  Nie udało się wyodrębnić danych")
            continue
        
        print(f"📊 Wyodrębnione dane:")
        print(f"   Imię: {extracted.get('scammer_name')}")
        print(f"   Telefon: {extracted.get('phone_number')}")
        print(f"   Konto: {extracted.get('bank_account')}")
        print(f"   Email: {extracted.get('email')}")
        print(f"   Confidence: {extracted.get('confidence')}")
        
        # Określ typ zgłoszenia i wartość docelową
        target_type = None
        target_value = None
        
        # Priorytet: telefon > konto > email
        if extracted.get('phone_number'):
            target_type = 'PERSON'
            target_value = extracted['phone_number']
        elif extracted.get('bank_account'):
            target_type = 'PERSON'
            target_value = extracted['bank_account']  # Użyjemy konta jako identyfikator
        
        if not target_type or not target_value:
            print("⚠️  Brak wystarczających danych do zgłoszenia")
            continue
        
        # Sprawdź czy już istnieje
        if api.check_if_exists(target_value, target_type):
            print(f"⏭️  Pomijam - {target_value} już jest w bazie")
            continue
        
        # Przygotuj dane zgłoszenia
        report_data = {
            'targetType': target_type,
            'targetValue': target_value,
            'rating': calculate_rating(extracted.get('confidence', 'medium')),
            'reason': map_scam_type_to_reason(
                extracted.get('scam_description', ''),
                extracted.get('screenshot_type', '')
            ),
            'comment': f"{extracted.get('scam_description', 'Oszustwo zgłoszone przez społeczność')}",
            
            # Dane OSINT
            'reportedEmail': extracted.get('email'),
            'facebookLink': extracted.get('facebook_link'),
            'screenshotUrl': img_url,
            
            # Dane osobowe oszusta
            'scammerName': extracted.get('scammer_name'),
            'bankAccount': extracted.get('bank_account'),
            
            # Metadane automatyzacji
            'isAutoGenerated': True,
            'sourceUrl': post['post_url']
        }
        
        # Wyślij do TrustCheck
        success = api.submit_report(report_data)
        
        if success:
            print(f"✅ DODANO ZGŁOSZENIE!")
            return True
    
    return False

def main():
    """Główna pętla scrapera"""
    print("""
╔══════════════════════════════════════════════════════╗
║      TrustCheck Auto-Scraper v1.0                    ║
║      Automatyczne wykrywanie oszustw                 ║
╚══════════════════════════════════════════════════════╝
    """)
    
    # Inicjalizacja modułów
    print("🔧 Inicjalizacja...")
    fb_scraper = FacebookScraper(Config.APIFY_API_KEY)
    vision = VisionProcessor(Config.OPENAI_API_KEY)
    api = TrustCheckAPI(Config.TRUSTCHECK_API_URL, Config.TRUSTCHECK_BOT_TOKEN)
    
    print("✅ Gotowe!\n")
    
    # Główna pętla
    while True:
        try:
            timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            print(f"\n🕐 [{timestamp}] Rozpoczynam skanowanie...")
            
            # 1. Scrapuj posty z Facebooka
            posts = fb_scraper.scrape_group_posts(
                Config.FACEBOOK_GROUP_URL,
                Config.MAX_POSTS_PER_RUN
            )
            
            # 2. Filtruj posty ze screenshotami
            posts_with_images = fb_scraper.filter_posts_with_screenshots(posts)
            
            # 3. Przetwarzaj każdy post
            processed = 0
            added = 0
            
            for post in posts_with_images:
                success = process_screenshot(post, vision, api)
                processed += 1
                if success:
                    added += 1
                
                # Pauza między requestami (aby nie przekroczyć limitów API)
                time.sleep(2)
            
            print(f"\n{'='*60}")
            print(f"📊 PODSUMOWANIE:")
            print(f"   Przetworzono: {processed} postów")
            print(f"   Dodano zgłoszeń: {added}")
            print(f"   Następne skanowanie za {Config.CHECK_INTERVAL_HOURS}h")
            print(f"{'='*60}\n")
            
            # Czekaj do następnego cyklu
            time.sleep(Config.CHECK_INTERVAL_HOURS * 3600)
            
        except KeyboardInterrupt:
            print("\n\n👋 Zatrzymano scraper. Do zobaczenia!")
            break
        except Exception as e:
            print(f"\n❌ Błąd krytyczny: {str(e)}")
            print("⏸️  Czekam 5 minut przed ponowną próbą...")
            time.sleep(300)

if __name__ == "__main__":
    main()
